/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GovernedBaseV2__factory } from "./GovernedBaseV2__factory";
export { GovernedV2__factory } from "./GovernedV2__factory";
export { IGovernanceSettings__factory } from "./IGovernanceSettings__factory";
