/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IProphet } from "./IProphet";
export type { MasterProphet } from "./MasterProphet";
export type { Ownable } from "./Ownable";
