/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GovernedBaseV2 } from "./GovernedBaseV2";
export type { GovernedV2 } from "./GovernedV2";
export type { IGovernanceSettings } from "./IGovernanceSettings";
