/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IOracleSwapCallee,
  IOracleSwapCalleeInterface,
} from "../../../../contracts/core/interfaces/IOracleSwapCallee";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount0",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount1",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "uniswapV2Call",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IOracleSwapCallee__factory {
  static readonly abi = _abi;
  static createInterface(): IOracleSwapCalleeInterface {
    return new utils.Interface(_abi) as IOracleSwapCalleeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IOracleSwapCallee {
    return new Contract(address, _abi, signerOrProvider) as IOracleSwapCallee;
  }
}
