/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20 } from "./IERC20";
export type { IMasterChef } from "./IMasterChef";
export type { IMiniChefV2 } from "./IMiniChefV2";
export type { IOracleSwapRewardsManager } from "./IOracleSwapRewardsManager";
export type { IRewarder } from "./IRewarder";
