/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as oracleSwapPairSol from "./OracleSwapPair.sol";
export * as interfaces from "./interfaces";
export { OracleSwapERC20__factory } from "./OracleSwapERC20__factory";
export { OracleSwapFactory__factory } from "./OracleSwapFactory__factory";
export { OracleSwapRouter__factory } from "./OracleSwapRouter__factory";
