/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ierc20Sol from "./IERC20.sol";
export type { ierc20Sol };
export type { IOracleSwapCallee } from "./IOracleSwapCallee";
export type { IOracleSwapERC20 } from "./IOracleSwapERC20";
export type { IOracleSwapFactory } from "./IOracleSwapFactory";
export type { IOracleSwapFtsoReward } from "./IOracleSwapFtsoReward";
export type { IOracleSwapManager } from "./IOracleSwapManager";
export type { IOracleSwapPair } from "./IOracleSwapPair";
export type { IOracleSwapRouter } from "./IOracleSwapRouter";
export type { IOracleSwapRouter01 } from "./IOracleSwapRouter01";
export type { IWETH } from "./IWETH";
