/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface OracleSwapRewardsManagerInterface extends utils.Interface {
  functions: {
    "flareContractRegistry()": FunctionFragment;
    "ftsoManager()": FunctionFragment;
    "ftsoProvider()": FunctionFragment;
    "ftsoRewardManager()": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "wnat()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "flareContractRegistry"
      | "ftsoManager"
      | "ftsoProvider"
      | "ftsoRewardManager"
      | "owner"
      | "renounceOwnership"
      | "transferOwnership"
      | "wnat"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "flareContractRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ftsoManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ftsoProvider",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ftsoRewardManager",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "wnat", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "flareContractRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ftsoManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ftsoProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ftsoRewardManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "wnat", data: BytesLike): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface OracleSwapRewardsManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: OracleSwapRewardsManagerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    flareContractRegistry(overrides?: CallOverrides): Promise<[string]>;

    ftsoManager(overrides?: CallOverrides): Promise<[string]>;

    ftsoProvider(overrides?: CallOverrides): Promise<[string]>;

    ftsoRewardManager(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    wnat(overrides?: CallOverrides): Promise<[string]>;
  };

  flareContractRegistry(overrides?: CallOverrides): Promise<string>;

  ftsoManager(overrides?: CallOverrides): Promise<string>;

  ftsoProvider(overrides?: CallOverrides): Promise<string>;

  ftsoRewardManager(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  wnat(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    flareContractRegistry(overrides?: CallOverrides): Promise<string>;

    ftsoManager(overrides?: CallOverrides): Promise<string>;

    ftsoProvider(overrides?: CallOverrides): Promise<string>;

    ftsoRewardManager(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    wnat(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    flareContractRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    ftsoManager(overrides?: CallOverrides): Promise<BigNumber>;

    ftsoProvider(overrides?: CallOverrides): Promise<BigNumber>;

    ftsoRewardManager(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    wnat(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    flareContractRegistry(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ftsoManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ftsoProvider(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ftsoRewardManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    wnat(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
