/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as oracleSwapPairSol from "./OracleSwapPair.sol";
export type { oracleSwapPairSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { OracleSwapERC20 } from "./OracleSwapERC20";
export type { OracleSwapFactory } from "./OracleSwapFactory";
export type { OracleSwapRouter } from "./OracleSwapRouter";
